### ISSUE TITLE
uh i found new way to bypass 45 min error

### ISSUE THREAD

**Issue by Minhe173** [Imagine-YT/Roblox-Account-Generator#11]
@RobloxArchiver @Imagine-YT

**Comment by Imagine-YT** [comment]
Hi

**Comment by RobloxArchiver** [comment]
> @RobloxArchiver @Imagine-YT

What is it? Current method is just using a proxy or VPN.

**Comment by Imagine-YT** [comment]
uh, I'll see about that. As of now I'm working on other projects, so yeah.

**Comment by Minhe173** [comment]
> 

no vpn/proxy

**Comment by Imagine-YT** [comment]
idk
