### ISSUE TITLE
Lupa (Python Lua) (SUGGESTION)

### ISSUE THREAD

**Issue by RobloxArchiver** [Imagine-YT/Roblox-Account-Generator#12]
Maybe [Lupa](https://pypi.org/project/lupa/) can be used to potentially provide better speeds? Lua is incredibly fast and certain tasks could definitely be written in it using Lupa to provide faster speeds. Just a suggestion though!

**Comment by Imagine-YT** [comment]
Well, I don't know Lua, so I won't use it in the near future, but thank you for your suggestion.
