### ISSUE TITLE
NopeCHA not working + cookies button not getting clicked

### ISSUE THREAD

**Issue by rylaz** [Imagine-YT/Roblox-Account-Generator#18]
The title says pretty much everything, nopeCHA presses the wrong things and when I start the script it crashes because it won't press "Accept All" cookies button

**Comment by cattotaco** [comment]
same issue here

**Comment by watahisho3** [comment]
y'all should try download the version 2.0

**Comment by cattotaco** [comment]
thats what we did

**Comment by Imagine-YT** [comment]
Project has been discontinued. I won't be posting updates on this anymore.
