### ISSUE TITLE
Not an issue i was able to fix the generator 

### ISSUE THREAD

**Issue by DROPLOTHUB** [Imagine-YT/Roblox-Account-Generator#24]
Fixed the Cookie Accept All error that kept making errors 
Added the most recent Chrome Driver to the solution

Here is the fixed source 
https://github.com/DROPLOTHUB/Roblox-account-generator  

but credit to the dude who made it first i hope u allow me to keep it on my git hub :)

**Comment by Imagine-YT** [comment]
Great Fix Buddy! But I can't merge this into my generator as I need a WORKING captcha bypasser which is free for all.
