### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by leopotty** [Imagine-YT/Roblox-Account-Generator#27]
I got a Problem by solving the Captcha at the Registration it stuck... could you help me there or could you sent me your discord?

**Comment by RobloxArchiver** [comment]
Did you get any errors? If not then I've experienced this before, I couldn't figure out a way to get around it. I'll message Imagine for you to see if we can figure out a fix. Any other issues?

**Comment by leopotty** [comment]
> 
idk it just stop at registration ... and load load load to create i think this captcha is not working

**Comment by jake4653** [comment]
mine is just stuck on login

**Comment by Imagine-YT** [comment]
As said on the page, I have discontinued the project, so I won't be updating the code. DO expect bugs, errors, etc.
