### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Yoko11111111** [Imagine-YT/Roblox-Account-Generator#3]
Not working closes instantly

**Comment by Minhe173** [comment]
try `pip install -r requirements.txt`

**Comment by Minhe173** [comment]
@Yoko11111111

**Comment by Minhe173** [comment]
@Imagine-YT ur termed lmao gimme ur new discord

**Comment by Imagine-YT** [comment]
@Minhe173 yea I got termed for no reason ._.
and @Yoko11111111 did you read everything in https://github.com/Imagine-YT/Roblox-Account-Generator/blob/main/READ%20ME%20FIRST.txt ?
If your issue still continues then you can explain further over here (CUZ MY DISCORD IS TERMED)

**Comment by Imagine-YT** [comment]
@Minhe173 
Add me: Imagine#1111
(my nitro is expiring soon so add me fast)
