### ISSUE TITLE
Generator Issue

### ISSUE THREAD

**Issue by PacketL0st** [Imagine-YT/Roblox-Account-Generator#35]
I'm probably just dumb but what am I doing wrong here? I tried contacting your via discord but they have since changed their username system. I was unable to install the requirements even after running the cmd prompt in the folder because 'pip' was not recognized. When I try running the generator, I get this issue. 
![image](https://github.com/Imagine-YT/Roblox-Account-Generator/assets/125250774/af644265-ffaf-4bf5-9215-5d86d76f0073)
Please advise what I am doing wrong and thank you for your time.

**Comment by Teslaguy2** [comment]
same happened with me

**Comment by Teslaguy2** [comment]
let me check at the error logs.

**Comment by Teslaguy2** [comment]
its one of the extensions causing the problem all i know

**Comment by Imagine-YT** [comment]
![image](https://github.com/Imagine-YT/Roblox-Account-Generator/assets/74649094/7ef7fac1-19c9-486b-9571-90261b22274e)
