### ISSUE TITLE
I'm really a beginner and I really don't know how to write, so could you teach me?

### ISSUE THREAD

**Issue by 2ctl** [Imagine-YT/Roblox-Account-Generator#36]
How do you use this? Please tell me. I would be really happy if you could tell me! :)

**Comment by Blitzedzz** [comment]
I can teach you add me on discord blitzedzz

**Comment by Imagine-YT** [comment]
![image](https://github.com/Imagine-YT/Roblox-Account-Generator/assets/74649094/a1a4685c-b9ab-47e6-9831-dcf7d32c7e23)
