### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by C4MMYYY0** [Imagine-YT/Roblox-Account-Generator#39]
thread 'main' panicked at 'Downloaded file cannot be uncompressed (xml extension)', src\files.rs:46:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace 

Im getting that nd then its closing

**Comment by Imagine-YT** [comment]
![image](https://github.com/Imagine-YT/Roblox-Account-Generator/assets/74649094/8752abe4-2407-4221-9b0f-b3bad59912eb)
